import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      gridTemplateColumns: {
        'grid-comwell': 'repeat(auto-fill, minmax(250px, 1fr))', 
      },
      gridColumn: {
        'span-4': 'span 4 / span 4',
      },
      fontFamily: {
        light: ["FelixLight", "sans-serif"],
        regular: ["FelixRegular", "sans-serif"],
        medium: ["FelixMedium", "sans-serif"],
        semibold: ["FelixSemiBold", "sans-serif"],
        bold: ["FelixBold", "sans-serif"],
        black: ["FelixBlack", "sans-serif"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      backgroundColor: {
        theme: "rgb(39, 58, 72)",
        theme2: "rgb(24, 43, 57)",
      },
      screens: {
        "3xl": "1920px",
        "2xl": '1536px',
        md: "1024px",
      },
      colors: {
        earth: {
          DEFAULT: "rgb(103, 113, 105)",
          "80": "rgb(128, 139, 130)",
          "60": "rgb(160, 171, 163)",
          "40": "rgb(192, 200, 194)",
          "20": "rgb(227, 230, 227)",
          "10": "rgb(238, 239, 238)",
        },
        sand: {
          DEFAULT: "rgb(170, 141, 101)",
          "80": "rgb(190, 161, 121)",
          "60": "rgb(215, 201, 185)",
          "40": "rgb(237, 227, 216)",
          "20": "rgb(240, 234, 226)",
          "10": "rgb(249, 246, 242)",
        },
        sea: {
          DEFAULT: "rgb(24, 43, 57)",
          "80": "rgb(39, 58, 72)",
          "60": "rgb(150, 150, 161)",
          "40": "rgb(197, 197, 203)",
          "20": "rgb(225, 225, 229)",
          "10": "rgb(243, 243, 245)",
        },
        charcoal: {
          DEFAULT: "rgb(22, 29, 32)",
          "80": "rgb(37, 44, 47)",
          "60": "rgb(159, 152, 152)",
          "40": "rgb(211, 209, 209)",
          "20": "rgb(234, 233, 231)",
          "10": "rgb(246, 244, 243)",
        },
        theme: {
          DEFAULT: "var(--color-charcoal)",
          "80": "var(--color-charcoal-80)",
          "60": "var(--color-charcoal-60)",
          "40": "var(--color-charcoal-40)",
          "20": "var(--color-charcoal-20)",
          "10": "var(--color-charcoal-10)",
        },
        "error-red": "rgb(235, 0, 38)",
        "success-green": "rgb(46, 204, 113)",
        "waiting-yellow": "rgb(241, 196, 15)",
      },
      spacing: {
        xs: ".5rem",
        sm: "1rem",
        md: "1.5rem",
      },
      fontSize: {
        "md:heading-huge": "66px",
        "heading-huge": "34px",
        "md:heading-xl": "46px",
        "heading-xl": "34px",
        "heading-lg": "36px",
        "heading-md": "28px",
        "heading-sm": "20px",
        "heading-xs": "16px",
        "heading-mini": "16px",
        body: "16px",
        "body-small": "13px",
        "body-large": "15px",
        link: "14px",
        rating: "15px",
        "lang-selector": "15px",
        "hotel-rating": "15px",
        trumpet: "13px",
        stat: "56px",
        label: "11px",
        "room-label": "13px",
        tab: "12px",
        navigation: "15px",
        price: "18px",
        "price-label": "13px",
        "price-club": "13px",
        "price-large": "28px",
        "price-strike": "28px",

        "md:heading-md": "28px",
        "md:heading-sm": "22px",
        "md:heading-xs": "18px",
        "md:heading-mini": "16px",
        "md:body": "16px",
        "md:body-small": "13px",
        "md:body-large": "15px",
        "md:link": "16px",
        "md:rating": "15px",
        "md:price": "28px",
      },
      lineHeight: {
        "heading-huge": "31px",
        "heading-xl": "31px",
        "heading-lg": "27px",
        "heading-md": "27px",
        "heading-sm": "20px",
        "heading-xs": "16px",
        "heading-mini": "16px",
        body: "15px",
        "body-small": "16px",
        "body-large": "22px",
        link: "15px",
        rating: "15px",
        "lang-selector": "15px",
        "hotel-rating": "15px",
        trumpet: "13px",
        stat: "50px",
        label: "10px",
        "room-label": "12px",
        tab: "12px",
        navigation: "15px",
        price: "17px",
        "price-label": "16.25px",
        "price-club": "16.25px",
        "price-large": "26.6px",
        "price-strike": "26.6px",
        "md:heading-huge": "59px",
        "md:heading-xl": "44px",
        "md:heading-lg": "32px",
        "md:heading-md": "27px",
        "md:heading-sm": "21px",
        "md:heading-xs": "17px",
        "md:heading-mini": "15px",
        "md:body": "15px",
        "md:body-small": "16px",
        "md:body-large": "22px",
        "md:link": "18px",
        "md:rating": "15px",
        "md:price": "28.6px",
      },
      letterSpacing: {
        "heading-huge": "-.02em",
        "heading-xl": "-.02em",
        "heading-lg": "-.02em",
        "heading-md": "-.02em",
        "heading-sm": "0em",
        "heading-xs": "0em",
        "heading-mini": "0em",
        body: "-.02em",
        "body-small": "0em",
        trumpet: ".02em",
        label: ".05em",
        "md:heading-huge": "-.02em",
        "md:heading-xl": "-.02em",
        "md:heading-lg": "-.02em",
        "md:heading-md": "-.02em",
        "md:heading-sm": "-.02em",
        "md:heading-xs": "-.02em",
        "md:heading-mini": "-.02em",
        "md:body": "-.02em",
        "md:body-small": "0em",
        "md:trumpet": ".02em",
      },
      fontWeight: {
        "body-large": "400",
        heading: "600",
        font: "400",
      },
    },
  },
  plugins:  [ ],
};
export default config;
