version: '3.8'

services:
 frontend-app:
    build: ./FrontEnd  
    ports:
      - '3000:3000'  # Next.js default port
    networks:
      - node-network

 node-app:
    build: ./BackEnd
    image: node-app
    environment:
      - MONGODB_URL=mongodb:27017
    ports:
      - '3006:3006'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network

 mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:


networks:
  node-network:
    driver: bridge
